server:
  port: ${SERVER_PORT:9000}
spring:
  application:
    name: notification-service

  kafka:
    bootstrap-servers: localhost:9092

    consumer:
      group-id: notification-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

      properties:
        spring.json.value.default.type: com.e2d.notification_service.DTO.TicketEvent
        spring.json.trusted.packages: "com.e2d.notification_service.DTO,e2d.ticketService.DTO"
        spring.json.use.type.headers: false

    listener:
      missing-topics-fatal: false

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:1eventxtest@gmail.com}
    password: ${MAIL_PASSWORD}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
