services:

  app:
    build: .
    container_name: e2d_auth
    ports:
      - "8081:8081"
    env_file:
      - .env
    depends_on:
      - mariadb
    networks:
      - e2d-net

  mariadb:
    image: mariadb:latest
    container_name: e2d_auth_db
    env_file:
      - .env
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_PASSWORD}
      MARIADB_DATABASE: ${DB_NAME}
    ports:
      - "${DB_PORT}:3306"
    healthcheck:
      test: [ "CMD", "healthcheck.sh", "--connect", "--innodb_initialized" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - e2d_auth_db:/var/lib/mysql
    networks:
      - e2d-net

networks:
  e2d-net:
    driver: bridge

volumes:
  e2d_auth_db: