server:
  port: ${SERVER_PORT:8081}

spring:
  application:
    name: auth

  datasource:
    hikari:
      connection-timeout: 30000
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:ticket_system}?currentSchema=${DB_SCHEMA:auth}
    username: ${DB_USER:ticket_user}
    password: ${DB_PASSWORD:1234}
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        default_schema: ${DB_SCHEMA:auth}
        format_sql: true

app:
  bootstrap:
    admin:
      username: ${ADMIN_USER:admin}
      password: ${ADMIN_PASSWORD}

logging:
  level:
    org.hibernate.SQL: ${SQL_LOG_LEVEL:DEBUG}
    org.hibernate.type.descriptor.sql: ${SQL_PARAM_LOG_LEVEL:TRACE}

jwt:
  secret: ${JWT_SECRET}
